### ISSUE TITLE
Clava's integration with Vitis HLS

### ISSUE THREAD

**Issue by tiagolascasas** [specs-feup/lara-framework#24]
Similar to our CMake integration, it would be nice if we could also have something similar for Vitis HLS.

This would work with a simple workflow: after we perform our HLS-related code transformations and directive insertion, we could synthesize the code with Vitis HLS, and parse the synthesis report into a JS-friendly format (i.e., JSON).

This would allow us to automatically estimate the performance of our transformed code using HLS, enabling processes like full Design Space Exploration in the near future.

## Possible API usage

```
// after code transformations
const vitis = new VitisHLS();

vitis.addSource("foo.c");
vitis.setTopFunction("matrix_multiply");
vitis.setPlatform("xcvu5p-flva2104-1-e");
vitis.setClock(10);

var success = vitis.synthesize();
if (success) {
    var report = vitis.parseReport();
    println("Design latency: " + report["latency"]);
}
```
## How to implement it

I think there is some intersectionality with the CMake extension, particularly when it comes to managing input files with the CMakerSources class. One idea could be to extract common functionality to a parent abstract class, and then to have extended classes for both CMake and Vitis HLS.

The integration with Vitis HLS itself is easy, as Vitis HLS works well as a command-line application and I already have the required scripts/commands to implement the entire flow, from creating a Vitis project to generating the synthesis report.

**Comment by lm-sousa** [comment]
We've had a student lined up for working in this. Not only for Vitis HLS but for other tools as well.
Unfortunately, he ended up accepting an offer by a company at the last minute.
We are planning to resubmit the proposal at the next call for PIs or MScs.
