### ISSUE TITLE
Choose documentation format/WebUI

### ISSUE THREAD

**Issue by joaobispo** [specs-feup/lara-framework#9]
Currently we are using a custom HTML generator that receives as input the populated documentation model. However, we could output instead to some markdown and use a website generator. Options include [Jekyll](https://jekyllrb.com/) (used by GitHub pages), [ReadTheDocs](https://readthedocs.org/), [DocPress](https://github.com/docpress/docpress), etc .

**Comment by lm-sousa** [comment]
New documentation is available at [specs-feup.github.io](https://specs-feup.github.io)
